/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTERA;

import DAO.ParqueaderoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class ActualizarParqueadero extends javax.swing.JFrame {

    /**
     * Creates new form CrearActualizarParqueadero
     */
    private ParqueaderoDAO pdao = new ParqueaderoDAO();
    
    public ActualizarParqueadero() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Parqueadero");
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbRegimen = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTipoParqueadero = new javax.swing.JComboBox();
        txtPoliza = new javax.swing.JTextField();
        txtTarifaBicicleta = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        txtTarifaAutomovil = new javax.swing.JTextField();
        txtTarifaMoto = new javax.swing.JTextField();
        btnActualizarParqueadero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbParqueaderoDatos = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("PARQUEADERO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tarifa Bicicleta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tipo de Parqueadero");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        cbRegimen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbRegimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comun", "Simplificado" }));
        jPanel1.add(cbRegimen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Régimen");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Dirección");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Teléfono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("No. Póliza");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        cbTipoParqueadero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbTipoParqueadero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En altura o subterráneo con dos o más niveles", "Subterráneo, un solo nivel y 50 cupos o más", "Subterráneo, un solo nivel con menos de 50 cupos", "A nivel, piso en concreto, asfalto o gravilla lavada de rio compactada, y con 50 cupos o más", "A nivel, piso en concreto, asfalto o gravilla lavada de rio compactada, y con menos de 50 cupos", "A nivel, pisos en afirmado o césped" }));
        jPanel1.add(cbTipoParqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 670, -1));

        txtPoliza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPoliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPolizaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 250, -1));

        txtTarifaBicicleta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTarifaBicicleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarifaBicicletaKeyTyped(evt);
            }
        });
        jPanel1.add(txtTarifaBicicleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 190, -1));

        txtRazonSocial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 250, -1));

        txtDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 250, -1));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 250, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Razon Social");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("NIT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tarifa Automóvil");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tarifa Motocicleta");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        txtNIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNITKeyTyped(evt);
            }
        });
        jPanel1.add(txtNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 250, -1));

        txtTarifaAutomovil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTarifaAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifaAutomovilActionPerformed(evt);
            }
        });
        txtTarifaAutomovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarifaAutomovilKeyTyped(evt);
            }
        });
        jPanel1.add(txtTarifaAutomovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 190, -1));

        txtTarifaMoto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTarifaMoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarifaMotoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTarifaMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 190, -1));

        btnActualizarParqueadero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActualizarParqueadero.setText("Actualizar Parqueadero");
        btnActualizarParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarParqueaderoActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarParqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 250, -1));

        tbParqueaderoDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbParqueaderoDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbParqueaderoDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbParqueaderoDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 840, 50));

        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPolizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPolizaActionPerformed

    private void btnActualizarParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarParqueaderoActionPerformed
        if(txtNIT.getText().equals("")||txtRazonSocial.getText().equals("")||txtDireccion.getText().equals("")||
                txtTelefono.getText().equals("")||txtPoliza.getText().equals("")||txtTarifaAutomovil.getText().equals("")||
                txtTarifaMoto.getText().equals("")||txtTarifaBicicleta.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        }else{
            String nit = txtNIT.getText();
            String razonSocial = txtRazonSocial.getText();
            String regimen = cbRegimen.getSelectedItem().toString();
            String direccion = txtDireccion.getText();
            String telefono = txtTelefono.getText();
            String poliza = txtPoliza.getText();
            String tipoParqueadero = cbTipoParqueadero.getSelectedItem().toString();
            double tarifaAutomovil = Double.parseDouble(txtTarifaAutomovil.getText());
            double tarifaMoto = Double.parseDouble(txtTarifaMoto.getText());
            double tarifaBicicleta = Double.parseDouble(txtTarifaBicicleta.getText());
            String mensaje = "";
            mensaje = pdao.actualizarParqueadero(nit, razonSocial, regimen, direccion, telefono, 
                        poliza, tipoParqueadero, tarifaAutomovil, tarifaMoto, tarifaBicicleta);
            JOptionPane.showMessageDialog(null, mensaje);
            mostrarTabla();
        }
    }//GEN-LAST:event_btnActualizarParqueaderoActionPerformed

    private void tbParqueaderoDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbParqueaderoDatosMouseClicked
        int select = tbParqueaderoDatos.getSelectedRow();
        txtNIT.setText(tbParqueaderoDatos.getValueAt(select, 0)+"");
        txtRazonSocial.setText(tbParqueaderoDatos.getValueAt(select, 1)+"");
        cbRegimen.setSelectedItem(tbParqueaderoDatos.getValueAt(select, 2)+"");
        txtDireccion.setText(tbParqueaderoDatos.getValueAt(select, 3)+"");
        txtTelefono.setText(tbParqueaderoDatos.getValueAt(select, 4)+"");
        txtPoliza.setText(tbParqueaderoDatos.getValueAt(select, 5)+"");
        cbTipoParqueadero.setSelectedItem(tbParqueaderoDatos.getValueAt(select, 6)+"");
        txtTarifaAutomovil.setText(tbParqueaderoDatos.getValueAt(select, 7)+"");
        txtTarifaMoto.setText(tbParqueaderoDatos.getValueAt(select, 8)+"");
        txtTarifaBicicleta.setText(tbParqueaderoDatos.getValueAt(select, 9)+"");
    }//GEN-LAST:event_tbParqueaderoDatosMouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Administrador a = new Administrador();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNITKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'||c>'9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtNITKeyTyped

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'||c>'9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTarifaAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifaAutomovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifaAutomovilActionPerformed

    private void txtTarifaAutomovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifaAutomovilKeyTyped
        char c = evt.getKeyChar();
        if(c!='.'&& (c<'0'||c>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtTarifaAutomovilKeyTyped

    private void txtTarifaMotoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifaMotoKeyTyped
        char c = evt.getKeyChar();
        if(c!='.'&& (c<'0'||c>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtTarifaMotoKeyTyped

    private void txtTarifaBicicletaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifaBicicletaKeyTyped
        char c = evt.getKeyChar();
        if(c!='.'&& (c<'0'||c>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtTarifaBicicletaKeyTyped

    /**
     * @param args the command line arguments
     */
    
    private void mostrarTabla(){
        pdao.listarParqueadero(tbParqueaderoDatos);
    }
    
    
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarParqueadero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarParqueadero;
    private javax.swing.JButton btnAtras;
    private javax.swing.JComboBox cbRegimen;
    private javax.swing.JComboBox cbTipoParqueadero;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbParqueaderoDatos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtPoliza;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtTarifaAutomovil;
    private javax.swing.JTextField txtTarifaBicicleta;
    private javax.swing.JTextField txtTarifaMoto;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
