/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTERA;

/**
 *
 * @author Carlos
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Administrador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionOperarios = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnGestionParqueadero = new javax.swing.JButton();
        btnGenerarInformes = new javax.swing.JButton();
        btnVerEstadisticas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ADMINISTRADOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, -1));

        btnGestionOperarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionOperarios.setText("Gestión de Operarios");
        btnGestionOperarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionOperariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionOperarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 230, -1));

        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 230, -1));

        btnGestionParqueadero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionParqueadero.setText("Gestión Parqueadero");
        btnGestionParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionParqueaderoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionParqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 230, -1));

        btnGenerarInformes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGenerarInformes.setText("Generar Informes");
        jPanel1.add(btnGenerarInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 230, -1));

        btnVerEstadisticas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVerEstadisticas.setText("Ver Estadísticas");
        jPanel1.add(btnVerEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionOperariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionOperariosActionPerformed
        GestionOperarios go = new GestionOperarios();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionOperariosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        FramePrincipal fp = new FramePrincipal();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGestionParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionParqueaderoActionPerformed
        ActualizarParqueadero ap = new ActualizarParqueadero();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionParqueaderoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGenerarInformes;
    private javax.swing.JButton btnGestionOperarios;
    private javax.swing.JButton btnGestionParqueadero;
    private javax.swing.JButton btnVerEstadisticas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
