/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTERA;

import DAO.ParqueaderoDAO;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class CrearParqueadero extends javax.swing.JFrame {

    /**
     * Creates new form CrearActualizarParqueadero
     */
    private ParqueaderoDAO pdao = new ParqueaderoDAO();
    
    public CrearParqueadero() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Parqueadero");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbRegimen = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTipoParqueadero = new javax.swing.JComboBox();
        txtPoliza = new javax.swing.JTextField();
        txtTarifaBicicleta = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        txtTarifaAutomovil = new javax.swing.JTextField();
        txtTarifaMoto = new javax.swing.JTextField();
        btnCrearParqueadero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("PARQUEADERO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tarifa Bicicleta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tipo de Parqueadero");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cbRegimen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbRegimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comun", "Simplificado" }));
        jPanel1.add(cbRegimen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Régimen");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Dirección");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Teléfono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("No. Póliza");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        cbTipoParqueadero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbTipoParqueadero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En altura o subterráneo con dos o más niveles", "Subterráneo, un solo nivel y 50 cupos o más", "Subterráneo, un solo nivel con menos de 50 cupos", "A nivel, piso en concreto, asfalto o gravilla lavada de rio compactada, y con 50 cupos o más", "A nivel, piso en concreto, asfalto o gravilla lavada de rio compactada, y con menos de 50 cupos", "A nivel, pisos en afirmado o césped" }));
        cbTipoParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoParqueaderoActionPerformed(evt);
            }
        });
        jPanel1.add(cbTipoParqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 670, -1));

        txtPoliza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 250, -1));

        txtTarifaBicicleta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTarifaBicicleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarifaBicicletaKeyTyped(evt);
            }
        });
        jPanel1.add(txtTarifaBicicleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 190, -1));

        txtRazonSocial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 250, -1));

        txtDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 250, -1));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 250, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Razon Social");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("NIT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tarifa Automóvil");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tarifa Motocicleta");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        txtNIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNITKeyTyped(evt);
            }
        });
        jPanel1.add(txtNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 250, -1));

        txtTarifaAutomovil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTarifaAutomovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarifaAutomovilKeyTyped(evt);
            }
        });
        jPanel1.add(txtTarifaAutomovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 190, -1));

        txtTarifaMoto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTarifaMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifaMotoActionPerformed(evt);
            }
        });
        txtTarifaMoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarifaMotoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTarifaMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 190, -1));

        btnCrearParqueadero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCrearParqueadero.setText("Crear Parqueadero");
        btnCrearParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearParqueaderoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearParqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearParqueaderoActionPerformed
        String mensaje = "";
        if(txtNIT.getText().equals("")||txtRazonSocial.getText().equals("")||txtDireccion.getText().equals("")||
                txtTelefono.getText().equals("")||txtPoliza.getText().equals("")||txtTarifaAutomovil.getText().equals("")||
                txtTarifaMoto.getText().equals("")||txtTarifaBicicleta.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        }else{
            String nit = txtNIT.getText();
            String razonSocial = txtRazonSocial.getText();
            String regimen = cbRegimen.getSelectedItem().toString();
            String direccion = txtDireccion.getText();
            String telefono = txtTelefono.getText();
            String poliza = txtPoliza.getText();
            String tipoParqueadero = cbTipoParqueadero.getSelectedItem().toString();
            double tarifaAutomovil = Double.parseDouble(txtTarifaAutomovil.getText());
            double tarifaMoto = Double.parseDouble(txtTarifaMoto.getText());
            double tarifaBicicleta = Double.parseDouble(txtTarifaBicicleta.getText());
            mensaje = pdao.insertarParqueadero(nit, razonSocial, regimen, direccion, telefono, 
                        poliza, tipoParqueadero, tarifaAutomovil, tarifaMoto, tarifaBicicleta);
            JOptionPane.showMessageDialog(null, mensaje);
        }
        if(mensaje=="Parqueadero guardado correctamente"){
            LoginAdmin la = new LoginAdmin();
            la.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCrearParqueaderoActionPerformed

    private void txtNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNITKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'|| c>'9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtNITKeyTyped

    private void cbTipoParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoParqueaderoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoParqueaderoActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'|| c>'9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTarifaAutomovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifaAutomovilKeyTyped
        char c = evt.getKeyChar();
        if(c!='.'&& (c<'0'||c>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtTarifaAutomovilKeyTyped

    private void txtTarifaMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifaMotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifaMotoActionPerformed

    private void txtTarifaMotoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifaMotoKeyTyped
        char c = evt.getKeyChar();
        if(c!='.'&& (c<'0'||c>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtTarifaMotoKeyTyped

    private void txtTarifaBicicletaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifaBicicletaKeyTyped
        char c = evt.getKeyChar();
        if(c!='.'&& (c<'0'||c>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtTarifaBicicletaKeyTyped
 
    private void limpiar(){
        txtNIT.setText("");
        txtRazonSocial.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtPoliza.setText("");
        txtTarifaAutomovil.setText("");
        txtTarifaMoto.setText("");
        txtTarifaBicicleta.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearParqueadero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearParqueadero;
    private javax.swing.JComboBox cbRegimen;
    private javax.swing.JComboBox cbTipoParqueadero;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtPoliza;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtTarifaAutomovil;
    private javax.swing.JTextField txtTarifaBicicleta;
    private javax.swing.JTextField txtTarifaMoto;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
